stages:      
  - test
  - build
  - deploy

test-crawler:     
  stage: test
  image: continuumio/miniconda3:4.3.27
  before_script:
    - pip install pipenv==2022.6.7
    - pipenv sync
    - python3 genenv.py
  script:
    - pipenv run pytest --cov-report term-missing --cov-config=.coveragerc --cov=./src/ tests/
  only:
      refs:
        - merge_requests
