version: '3.0'
services:
  crawler_twse:
    image: louisekr/crawler:${GIT_TAG}
    hostname: 'twse'
    command: pipenv run celery -A src.tasks.worker worker --loglevel=info --concurrency=1 --hostname=%h -Q twse_crawler
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.crawler_twse == true]
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network
    
  crawler_tpex:
    image: crawler:1.0.1
    hostname: 'tpex'
    command: pipenv run celery -A src.tasks.worker worker --loglevel=info --concurrency=1 --hostname=%h -Q tpex_crawler
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network
    
  crawler_taifex:
    image: crawler:1.0.1
    hostname: 'taifex'
    command: pipenv run celery -A src.tasks.worker worker --loglevel=info --concurrency=1 --hostname=%h -Q taifex_crawler
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network

networks:
  my_network:
    external: true


