version: '3.3'
services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: financialdata
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.mysql == true]
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    links:
      - mysql:db
    ports:
      - 8080:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
    depends_on:
      - mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.mysql == true]
    networks:
      - my_network

networks:
  my_network:
    external: true

volumes:
  mysql:
    external: true